# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da2de0d620895640794be8c8b0f558e064d6b943f84148dfbdbdf49e71bd24989dd330976ae3a900417dc07afca9a800b97878eccb4f3f2b1282ea795b886b5f

test:
  secret_key_base: dfd38d2f8d310513deb176df16a91f2da88f7da324436952bde0fc2e10ca0acc62cba1a290701d19a73e7c8dc5131db4a18525af37f073c34c02dbed88acc309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
